# Generated by Django 4.1.7 on 2023-04-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="iof_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
